 - name: Swtich nginx stream/module 
   shell:
     cmd: dnf module enable -y nginx:{{ nginx_version_stream }}
     warn: false

#  - name: Install container tools 
#    shell:
#      cmd: dnf module install -y container-tools
#      warn: false

 - name: install podman
   dnf:
    name: podman
    state: latest
    install_weak_deps: yes

 - name: install slirp4netns
   dnf:
    name: slirp4netns
    state: latest
    install_weak_deps: yes

 - name: install nginx
   dnf:
    name: nginx
    state: latest

 - name: install vim
   dnf:
    name: vim
    state: latest

 - name: install htop
   dnf:
    name: htop
    state: latest

 - name: Install python3
   dnf:
    name: python3
    state: latest

 - name: Install pip3
   dnf:
    name: python3-pip
    state: latest

 - name: Install python3-virtualenv
   dnf:
    name: python3-virtualenv
    state: latest

 - name: Install stunnel
   dnf:
    name: stunnel
    state: latest
   when: enable_airsonic_proxy|bool